### ISSUE TITLE
Add `foldMapWithKey`

### ISSUE THREAD

**Issue by blamario** [jonathanknowles/monoidmap#207]
I'm looking at using  `monoidmap` in one of my projects, and one thing (perhaps not the only one!) is the lack of the `foldMapWithKey` function. I don't see any reason it can't be added.

**Comment by jonathanknowles** [comment]
Thanks @blamario, I agree that is something we could easily provide.
 
Since the basic folding functions are provided through the `Foldable` instance, I did wonder about the possibility of just providing an instance of a (standard) class that already has a `foldMapWithKey` function.

I found two obvious candidates:
- [`FoldableWithKey.foldMapWithKey`](https://hackage.haskell.org/package/keys-3.12.4/docs/Data-Key.html#v:foldMapWithKey) from the [`keys`](https://hackage.haskell.org/package/keys-3.12.4/) package.
- [`FoldableWithIndex.ifoldMap`](https://hackage.haskell.org/package/indexed-traversable-0.1.4/docs/Data-Foldable-WithIndex.html#v:ifoldMap) from the [`indexed-traversable`](https://hackage.haskell.org/package/indexed-traversable-0.1.4/) package.
  
However, both of these packages have non-trivial dependency footprints.

Perhaps a simple solution would be to just provided coerced versions of the folding functions already provided by `Data.Map.Strict`?

I've drafted a PR here: https://github.com/jonathanknowles/monoidmap/pull/208

Would be interested to hear your thoughts!

**Comment by blamario** [comment]
In your place, I'd just export the coerced functions rather than expand the dependency footprint. At a glance, the reverse dependencies of the two packages tend to use the methods on concrete instance types rather than build on the abstraction. Besides, as long as the function names match those from the `keys` package methods, you can always change your mind without breaking the backward compatibility. Your PR seems fine, though I'm surprised that the `coerce`s require explicit type signatures.

**Comment by jonathanknowles** [comment]
> In your place, I'd just export the coerced functions rather than expand the dependency footprint. At a glance, the reverse dependencies of the two packages tend to use the methods on concrete instance types rather than build on the abstraction.

Thanks, it's good to have a second opinion!

> Besides, as long as the function names match those from the `keys` package methods, you can always change your mind without breaking the backward compatibility.

Nice point.

> Your PR seems fine

Thanks for having a look!

> though I'm surprised that the `coerce`s require explicit type signatures.

I also wonder if there's a simpler way. Of course, we could replace these with combinations of `fmap` and `toMap` (which is just a synonym for `coerce`) , but I'm not as confident that such conversions would still be zero-cost.

On the other hand, these explicit type signatures seem similar to what generalised newtype deriving generates (under the hood): https://gitlab.haskell.org/ghc/ghc/-/wikis/roles#generalizednewtypederiving-implemented-using-coerce

**Comment by jonathanknowles** [comment]
Hi @blamario 

Just to let you know, `foldMapWithKey` is now available [here](https://hackage.haskell.org/package/monoidmap-0.0.1.7/docs/Data-MonoidMap.html#v:foldMapWithKey) in [`monoidmap-0.0.1.7`](https://hackage.haskell.org/package/monoidmap-0.0.1.7). Thanks again for suggesting this.

Wishing you a happy new year!
